import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Start a transaction
  await prisma.$transaction(async (prisma) => {
    // Delete existing data
    await prisma.product.deleteMany();
    await prisma.category.deleteMany();

    // Seed categories
    await prisma.category.createMany({
      data: [
        { id: 1, name: 'TODOS' },
        { id: 2, name: 'ANIMES' },
        { id: 3, name: 'JOGOS' },
        { id: 4, name: 'FOFO' },
        { id: 5, name: 'RELIGIOSO' },
        { id: 6, name: 'GEEK' },
        { id: 7, name: 'PRINCESAS' },
        { id: 8, name: 'HERÓIS' },
      ],
    });

    // Query the categories to ensure they were created
    const categories = await prisma.category.findMany();
    console.log('Categories:', categories);

    // Seed products
    await prisma.product.createMany({
      data: [
        {
          created_at: 9,
          description: [
            '°❀⋆.ೃ࿔*:･ Xiao em crochê!',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '0FPWMFbdFS0WCw08EKYP',
          media: ['https://i.ibb.co/4TJFT9n/xiaoHD.jpg'],
          link: 'https://shopee.com.br/Xiao-em-Croch%C3%AA-Amigurumi-de-Genshin-Impact-i.623543065.22192871568?sp_atk=6c33d3a7-3620-461e-905a-8fcf0456b902&xptdk=6c33d3a7-3620-461e-905a-8fcf0456b902',
          price: 165.9,
          product_group: 'Genshin Impact',
          purchase_count: 1,
          rating: 2,
          tag: 'Xiao - Genshin Impact',
          title: 'Xiao - Genshin Impact',
          category_id: 3,
        },
        {
          created_at: 1,
          description: [
            '₊˚ʚ 🌱 ₊˚✧ﾟ. Chaveiro Mini Porquinho em Crochê! ೀ⋆｡🌷',
            'Tem aproximadamente de 6 a 7 cm, e enchimento de fibra siliconada antialérgica.',
          ],
          id: '0qpGD7r2fnZlaLGt8Kz0',
          media: ['https://i.ibb.co/P1QQ3cN/porquinho-img.jpg'],
          link: 'https://shopee.com.br/Chaveiro-Mini-Porquinho-em-Croch%C3%AA-Amigurumi-Crochet-i.623543065.22297281398?sp_atk=71e21fc6-b091-453b-be0e-480147ad4400&xptdk=71e21fc6-b091-453b-be0e-480147ad4400',
          price: 21.5,
          product_group: 'animals',
          purchase_count: 1,
          rating: 0,
          tag: 'Porquinho Animais',
          title: 'Porquinho',
          category_id: 4,
        },
        {
          created_at: 3,
          description: [
            '°❀⋆.ೃ࿔*:･ Viper em crochê!',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '12ghKAqcJ7U2hLkf2Myw',
          media: ['https://i.ibb.co/gvWnnxC/viper-img.jpg'],
          link: 'https://shopee.com.br/Viper-em-Croch%C3%AA-Amigurumi-de-Valorant-i.623543065.19097615701?sp_atk=e2b26897-ab8d-4877-be56-a547dd835d03&xptdk=e2b26897-ab8d-4877-be56-a547dd835d03',
          price: 92.9,
          product_group: 'Valorant',
          purchase_count: 0,
          rating: 0,
          tag: 'Viper - Valorant',
          title: 'Viper - Valorant',
          category_id: 3,
        },
        {
          created_at: 2,
          description: [
            ' ⋆｡ﾟ🔍⋆｡🕵🏻‍♂️｡⋆ O espião da família Forger em crochê! Loid Forger! ๋࣭ ⭑⚝',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '1AhRQOPz0bCC11fJwqUa',
          media: ['https://i.ibb.co/tbfKX4d/loid-img.jpg'],
          link: 'https://shopee.com.br/Loid-Forger-em-Croch%C3%AA-Amigurumi-de-Spy-X-Family-Anya-Yor-Chaveiro-i.623543065.23597287072?sp_atk=e0d4ed59-71d0-46f8-871c-10d91b2836c1&xptdk=e0d4ed59-71d0-46f8-871c-10d91b2836c1',
          price: 92.9,
          product_group: 'Spy x Family',
          purchase_count: 0,
          rating: 0,
          tag: 'Loid Forger - Spy x Family',
          title: 'Loid Forger - Spy x Family',
          category_id: 2,
        },
        {
          created_at: 7,
          description: [
            'Homem Aranha em Crochê! 🕸️🕷️',
            'Tem aproximadamente 8 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '1rVNX3h7mZDr2vX9pxf0',
          media: ['https://i.ibb.co/Tt1VHms/miranha-img.jpg'],
          link: 'https://shopee.com.br/Homem-Aranha-em-Croch%C3%AA-Chaveiro-de-Amigurumi-i.623543065.22397337991?sp_atk=559026cd-6926-4dc8-89d3-39dd634f3dc4&xptdk=559026cd-6926-4dc8-89d3-39dd634f3dc4',
          price: 26.9,
          product_group: 'Heroes',
          purchase_count: 1,
          rating: 0,
          tag: 'Homem Aranha - Vingadores',
          title: 'Homem Aranha - Vingadores',
          category_id: 8,
        },
        {
          created_at: 5,
          description: [
            '°❀⋆.ೃ࿔*:･ Giyu Tomioka em crochê! ',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '1topD8JNQ0yBeQ9hdy9X',
          media: ['https://i.ibb.co/KGBcSs4/giyu-img.jpg'],
          link: 'https://shopee.com.br/Giyu-Tomioka-em-Croch%C3%AA-Amigurumi-de-Demon-Slayer-i.623543065.22297357880?sp_atk=1eaecfba-26bd-4eb1-8769-4b029144f594&xptdk=1eaecfba-26bd-4eb1-8769-4b029144f594',
          price: 83.9,
          product_group: 'Demon Slayer',
          purchase_count: 1,
          rating: 0,
          tag: 'Giyu Tomioka - Demon Slayer Kimetsu no Yaiba',
          title: 'Giyu Tomioka - Demon Slayer',
          category_id: 2,
        },
        {
          created_at: 9,
          description: [
            '°❀⋆.ೃ࿔*:･ Zhongli em crochê!',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '1xduorqoT5TaOW3xKnnV',
          media: ['https://i.ibb.co/KWbyDrf/zhongli-img.jpg'],
          link: 'https://shopee.com.br/Zhongli-em-Croch%C3%AA-Amigurumi-de-Genshin-Impact-i.623543065.22192871502?sp_atk=cf998dca-0e8a-42ac-97b2-8efa99fb5428&xptdk=cf998dca-0e8a-42ac-97b2-8efa99fb5428',
          price: 165.9,
          product_group: 'Genshin Impact',
          purchase_count: 0,
          rating: 0,
          tag: 'Zhongli - Genshin Impact',
          title: 'Zhongli - Genshin Impact',
          category_id: 3,
        },
        {
          created_at: 5,
          description: [
            '°❀⋆.ೃ࿔*:･ Muichiro Tokito em Crochê!',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '2TauUyRkjQRAtGcAxZMU',
          media: ['https://i.ibb.co/rb5Yqrg/muichiro-img.jpg'],
          link: 'https://shopee.com.br/Muichiro-Tokito-em-Croch%C3%AA-Amigurumi-de-Demon-Slayer-i.623543065.22592856199?sp_atk=a22e185f-1131-498f-8ea2-644a3cdef736&xptdk=a22e185f-1131-498f-8ea2-644a3cdef736',
          price: 83.9,
          product_group: 'Demon Slayer',
          purchase_count: 1,
          rating: 0,
          tag: 'Muichiro Tokito - Demon Slayer Kimetsu no Yaiba',
          title: 'Muichiro - Demon Slayer',
          category_id: 2,
        },
        {
          created_at: 9,
          description: [
            '°❀⋆.ೃ࿔*:･ Kazuha em crochê!',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '2szrc8aOfjldBQRm90rC',
          media: ['https://i.ibb.co/Z2hMpCH/kaedehara-kazuha-img.jpg'],
          link: 'https://shopee.com.br/Kaedehara-Kazuha-em-Croch%C3%AA-Amigurumi-de-Genshin-Impact-i.623543065.18697661590?sp_atk=d5153e67-1d50-428f-8549-ef987c7db006&xptdk=d5153e67-1d50-428f-8549-ef987c7db006',
          price: 169.9,
          product_group: 'Genshin Impact',
          purchase_count: 0,
          rating: 0,
          tag: 'Kaedehara Kazuha em Crochê Amigurumi de Genshin Impact',
          title: 'Kazuha - Genshin Impact',
          category_id: 3,
        },
        {
          created_at: 9,
          description: [
            '°❀⋆.ೃ࿔*:･ Nahida em Crochê!  A mini arconte agora disponível para venda na loja!',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '3HOhcbFJqloQhg4ihB6G',
          media: [
            'https://i.ibb.co/vBws4pN/nahida-1.jpg',
            'https://i.ibb.co/8X0gnzS/nahida-2.jpg',
            'https://i.ibb.co/4R68zHy/nahida-3.jpg',
            'https://i.ibb.co/z7Z24sB/nahida-4.jpg',
            'https://i.ibb.co/vDQPjNc/nahida-5.jpg',
            'https://i.ibb.co/yq4tHCs/nahida-6.jpg',
          ],
          link: 'https://shopee.com.br/Nahida-Lorde-Menor-Kusanali-em-Croch%C3%AA-Amigurumi-de-Genshin-Impact-i.623543065.23997355399?sp_atk=38509db2-c00e-4082-8287-d09c0705cfa2&xptdk=38509db2-c00e-4082-8287-d09c0705cfa2',
          price: 165.9,
          product_group: 'Genshin Impact',
          purchase_count: 1,
          rating: 0,
          tag: 'Lorde Menor Kusanali Nahida - Genshin Impact',
          title: 'Nahida - Genshin Impact',
          category_id: 3,
        },
        {
          created_at: 12,
          description: [
            '°❀⋆.ೃ࿔*:･ Frieren em crochê °❀⋆.ೃ࿔*:･',
            'Versão maior com aproximadamente 15 cm, versão chaveiro com aproximadamente 6 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '3VlG9TDa9IPxjqPj4rLP',
          media: ['https://i.ibb.co/hdpKtPN/frieren-img.jpg'],
          link: 'https://shopee.com.br/Frieren-em-Croch%C3%AA-Amigurumi-de-Sou-Frieren-Sousou-no-Frieren-i.623543065.23697413376?sp_atk=f8c371a1-c114-4d2d-b247-63e0a0e23169&xptdk=f8c371a1-c114-4d2d-b247-63e0a0e23169',
          price: 139.9,
          product_group: 'Sousou no Frieren',
          purchase_count: 3,
          rating: 0,
          tag: 'Frieren em Crochê Amigurumi de Sousou no Frieren',
          title: 'Frieren - Sousou no Frieren',
          category_id: 2,
        },
        {
          created_at: 4,
          description: [
            '°❀⋆.ೃ࿔*:･ Nami em crochê! Opção Funko e Tradicional!',
            'Personagens com aproximadamente 12 e 15 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '4FBbqLULpQviQCgp12fN',
          media: ['https://i.ibb.co/pJ89Smx/nami-img.jpg'],
          link: 'https://shopee.com.br/Nami-em-Croch%C3%AA-Amigurumi-de-One-Piece-i.623543065.23697307702?sp_atk=16ac2690-bcdb-4fcc-9008-7930339bed40&xptdk=16ac2690-bcdb-4fcc-9008-7930339bed40',
          price: 49.9,
          product_group: 'One Piece',
          purchase_count: 0,
          rating: 0,
          tag: 'Nami - One Piece',
          title: 'Nami - One Piece',
          category_id: 2,
        },
        {
          created_at: 9,
          description: [
            '°❀⋆.ೃ࿔*:･ Alhaitham em crochê!',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '6Shy5999Hl8CXS4CN5GF',
          media: [
            'https://i.ibb.co/GCSrSNv/alh]aitham-1.jpg',
            'https://i.ibb.co/6n055Tz/alhaitham-2.jpg',
            'https://i.ibb.co/HGtDMMY/alhaitham-3.jpg',
            'https://i.ibb.co/wNwZGvg/alhaitham-4.jpg',
            'https://i.ibb.co/Y846nqM/alhaitham-5.jpg',
            'https://i.ibb.co/9qzT54J/alhaitham-6.jpg',
            'https://i.ibb.co/kSLgcrg/alhaitham-77.jpg',
          ],
          link: 'https://shopee.com.br/Alhaitham-em-Croch%C3%AA-Amigurumi-de-Genshin-Impact-i.623543065.22192954444?sp_atk=6a6108fe-0a05-4693-946a-9876fda9a22e&xptdk=6a6108fe-0a05-4693-946a-9876fda9a22e',
          price: 189.9,
          product_group: 'Genshin Impact',
          purchase_count: 0,
          rating: 0,
          tag: 'Alhaitham - Genshin Impact',
          title: 'Alhaitham em Crochê',
          category_id: 3,
        },
        {
          created_at: 1,
          description: [
            'Saitama feito em crochê!',
            'Tem aproximadamente de 15 cm e enchimento de fibra siliconada antialérgica.',
          ],
          id: '7fjmvTCN2VwFznk6nEge',
          media: ['https://i.ibb.co/RNq7jJt/saitama-img.jpg'],
          link: 'https://shopee.com.br/Saitama-em-Croch%C3%AA-Amigurumi-de-One-Punch-Man-i.623543065.22797290075?sp_atk=62a109a7-5e15-415f-a18c-3ed281f9a252&xptdk=62a109a7-5e15-415f-a18c-3ed281f9a252',
          price: 39.9,
          product_group: 'One Punch-Man',
          purchase_count: 1,
          rating: 0,
          tag: 'Saitama - One Punch-Man',
          title: 'Saitama - One Punch-Man',
          category_id: 2,
        },
        {
          created_at: 1,
          description: [
            '𓍢ִ໋🌷͙֒✧˚ ༘ ⋆｡˚♡ Abelhinha em crochê! Uma fofura para enfeitar o quarto ou usar de chaveiro! -`♡´-',
            'Tem aproximadamente 10 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '84oAqOR6AkaALoCHCXJk',
          media: ['https://i.ibb.co/D9qWXtm/abelinha-img.jpg'],
          link: 'https://shopee.com.br/Abelhinha-Fofa-em-Croch%C3%AA-Amigurumi-de-Abelha-i.623543065.20597604725?sp_atk=62a90e15-0cec-476d-86a1-46cd36861c59&xptdk=62a90e15-0cec-476d-86a1-46cd36861c59',
          price: 35.5,
          product_group: 'animals',
          purchase_count: 0,
          rating: 0,
          tag: 'Abelinha Fofa Animais',
          title: 'Abelinha Fofa',
          category_id: 4,
        },
        {
          created_at: 4,
          description: [
            '°❀⋆.ೃ࿔*:･ Luffy em crochê!',
            'Personagens com entre 12 e 15 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '90Qz7mMTZlRhMFqpd1Jm',
          media: ['https://i.ibb.co/gSBW05s/luffy-img.jpg'],
          link: 'https://shopee.com.br/Luffy-em-Croch%C3%AA-Amigurumi-de-One-Piece-i.623543065.19699188158?sp_atk=3a3915ca-23fb-49bf-8e32-e79f1b1a0d33&xptdk=3a3915ca-23fb-49bf-8e32-e79f1b1a0d33',
          price: 52.5,
          product_group: 'One Piece',
          purchase_count: 1,
          rating: 0,
          tag: 'Monkey D. Luffy - One Piece',
          title: 'Luffy - One Piece',
          category_id: 2,
        },
        {
          created_at: 6,
          description: [
            '⋆｡ﾟ☁︎｡⋆｡ ﾟ☾ ﾟ｡⋆ Sailor Moon em crochê!',
            'Tem aproximadamente de 22 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: '9FbaF2jJKTEmrjPuvCAB',
          media: ['https://i.ibb.co/bN65Zpz/sailor-moon-img.jpg'],
          link: 'https://shopee.com.br/Sailor-Moon-em-Croch%C3%AA-Amigurumi-i.623543065.23292828214?sp_atk=323b9cbf-cd1e-4cac-a870-6eaf0d15bfe6&xptdk=323b9cbf-cd1e-4cac-a870-6eaf0d15bfe6',
          price: 139.9,
          product_group: 'Sailor Moon',
          purchase_count: 1,
          rating: 0,
          tag: 'Sailor Moon',
          title: 'Sailor Moon',
          category_id: 2,
        },
        {
          created_at: 11,
          description: [
            '°❀⋆.ೃ࿔*:･ Jinx em crochê!',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'B6oC2rmauf5wi1CU1uLx',
          media: ['https://i.ibb.co/NThj1gx/jinx-img.jpg'],
          link: 'https://shopee.com.br/Jinx-em-Croch%C3%AA-Amigurumi-de-League-Of-Legends-LOL-i.623543065.23397408509?xptdk=b0fec0d1-217b-4b36-a0c7-ed199da800d7',
          price: 109.9,
          product_group: 'League of Legends',
          purchase_count: 0,
          rating: 0,
          tag: 'Jinx em Crochê Amigurumi de League Of Legends LOL',
          title: 'Jinx - League of Legends',
          category_id: 3,
        },
        {
          created_at: 10,
          description: [
            'Nossa senhora de Lourdes + Bernadette em Crochê.',
            'Acompanha grutinha e terço!',
            'Nossa senhora com a gruta tem aproximadamente de 26 cm , e Bernadette tem 12 cm aproximadamente, todas com olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'BdbE7WoTNFPOSBueybdQ',
          media: ['https://i.ibb.co/4FGdkMT/lurdes-bernadete-img.jpg'],
          link: 'https://shopee.com.br/Nossa-Senhora-de-Lourdes-e-Bernadette-em-Croch%C3%AA-Amigurumi-Religioso-i.623543065.23992884226?sp_atk=11778836-ba08-4d8a-832d-3b56e3651efd&xptdk=11778836-ba08-4d8a-832d-3b56e3651efd',
          price: 229.9,
          product_group: 'Religious',
          purchase_count: 1,
          rating: 0,
          tag: 'Nossa Senhora de Lourdes e Bernadette Santa Religioso Católico Católica Catolico Catolica',
          title: 'Nossa Senhora de Lourdes e Bernadette',
          category_id: 5,
        },
        {
          created_at: 4,
          description: [
            '°❀⋆.ೃ࿔*:･ Zoro em crochê! Versão tradicional e versão funko.',
            'Personagens com aproximadamente entre 12 e 15 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'DR1PaHnBbrfCB4fJQOtj',
          media: ['https://i.ibb.co/3FmhcyF/zoro-img.jpg'],
          link: 'https://shopee.com.br/Zoro-em-Croch%C3%AA-Amigurumi-de-One-Piece-i.623543065.23492810930?sp_atk=7dde948b-a293-4a8c-b86a-81a4ac9b5e2b&xptdk=7dde948b-a293-4a8c-b86a-81a4ac9b5e2b',
          price: 49.9,
          product_group: 'One Piece',
          purchase_count: 0,
          rating: 0,
          tag: 'Roronoa Zoro - One Piece',
          title: 'Zoro - One Piece',
          category_id: 2,
        },
        {
          created_at: 3,
          description: [
            '°❀⋆.ೃ࿔*:･ Killjoy em Crochê!',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'DUQty7TUbWFRGLcPcn3J',
          media: ['https://i.ibb.co/nD9NZd3/killjoy-img.jpg'],
          link: 'https://shopee.com.br/Killjoy-em-croch%C3%AA-Amigurumi-de-Valorant-i.623543065.23292810791?sp_atk=5fcec207-e90a-48ca-9665-1390675fb6ee&xptdk=5fcec207-e90a-48ca-9665-1390675fb6ee',
          price: 92.9,
          product_group: 'Valorant',
          purchase_count: 0,
          rating: 0,
          tag: 'Killjoy - Valorant',
          title: 'Killjoy - Valorant',
          category_id: 3,
        },
        {
          created_at: 1,
          description: [
            'Mini Mike Wazowski em Crochê! ',
            'Tem aproximadamente de 5 a 6 cm, e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'E06ge0rFG3bBYCJMGKtq',
          media: ['https://i.ibb.co/SvJBHvV/mike-img.jpg'],
          link: 'https://shopee.com.br/Mini-Mike-Wazowski-em-Croch%C3%AA-Amigurumi-Monstros-S.A.-SA-Chaveiro-i.623543065.22297281341?sp_atk=663de6b5-421c-43c7-90f7-b01bc73da5d4&xptdk=663de6b5-421c-43c7-90f7-b01bc73da5d4',
          price: 24.9,
          product_group: 'Monstros S.A.',
          purchase_count: 1,
          rating: 0,
          tag: 'Mini Mike Wazowski Monstros S.A SA',
          title: 'Mini Mike Wazowski',
          category_id: 6,
        },
        {
          created_at: 4,
          description: [
            '°❀⋆.ೃ࿔*:･ Sanji em crochê! Versão Funko e Versão Tradicional!',
            'Personagens com aproximadamente 12 e 15 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'FB2Io8ydPwVLCmohQTp2',
          media: ['https://i.ibb.co/RzLyD6M/sanji-img.jpg'],
          link: 'https://shopee.com.br/Sanji-em-Croch%C3%AA-Amigurumi-de-One-Piece-i.623543065.22997302733?sp_atk=e51ef018-a6df-4786-aa40-16007b9f41e1&xptdk=e51ef018-a6df-4786-aa40-16007b9f41e1',
          price: 49.9,
          product_group: 'One Piece',
          purchase_count: 0,
          rating: 0,
          tag: 'Vinsmoke Sanji - One Piece',
          title: 'Sanji - One Piece',
          category_id: 2,
        },
        {
          created_at: 9,
          description: [
            '°❀⋆.ೃ࿔*:･ Furina em Crochê! ',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'FClEI2CvMl8FmHYt6zc5',
          media: ['https://i.ibb.co/rHzJTBR/furina-img.jpg'],
          link: 'https://shopee.com.br/Furina-em-Croch%C3%AA-Amigurumi-de-Genshin-Impact-i.623543065.18297629239?sp_atk=a82b82d3-5603-437b-9ae0-dae3a32e4e03&xptdk=a82b82d3-5603-437b-9ae0-dae3a32e4e03',
          price: 165.9,
          product_group: 'Genshin Impact',
          purchase_count: 0,
          rating: 0,
          tag: 'Furina de Fontaine - Genshin Impact',
          title: 'Furina - Genshin Impact',
          category_id: 3,
        },
        {
          created_at: 1,
          description: [
            '‧₊˚✧ Chaveiro de gatinho segurando coração! ❤️‍🩹 ♡ ✧˚₊‧',
            'Tem aproximadamente 8 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'GEowtFCOyaVsYReAxQ0I',
          media: [
            'https://i.ibb.co/1Jx7YSK/gatinho-1.jpg',
            'https://i.ibb.co/P1rNpWz/gatinho-img.jpg',
            'https://i.ibb.co/2k9M3R8/gatinho-3.jpg',
          ],
          link: 'https://shopee.com.br/Chaveiro-de-Gatinho-com-cora%C3%A7%C3%A3o-em-Croch%C3%AA-Amigurumi-i.623543065.20097609426?sp_atk=f314759e-03de-4ef6-9e84-732af7146c87&xptdk=f314759e-03de-4ef6-9e84-732af7146c87',
          price: 24.5,
          product_group: 'animals',
          purchase_count: 6,
          rating: 0,
          tag: 'Chaveiro de Gatinho - Animais',
          title: 'Chaveiro de Gatinho',
          category_id: 4,
        },
        {
          created_at: 9,
          description: [
            '°❀⋆.ೃ࿔*:･ Fu Xuan em crochê!',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'IKaf3s5NomErXNy0VM6r',
          media: ['https://i.ibb.co/wcL1chy/fu-xuan-img.jpg'],
          link: 'https://shopee.com.br/Fu-Xuan-em-Croch%C3%AA-Amigurumi-de-Honkai-i.623543065.22397363138?sp_atk=dbab8e72-e9bc-45fe-8480-668ca1dd5f9a&xptdk=dbab8e72-e9bc-45fe-8480-668ca1dd5f9a',
          price: 165.9,
          product_group: 'Genshin Impact',
          purchase_count: 0,
          rating: 0,
          tag: 'Fu Xuan - Honkai Impact',
          title: 'Fu Xuan - Honkai Impact',
          category_id: 3,
        },
        {
          created_at: 3,
          description: [
            '°❀⋆.ೃ࿔*:･ Jett em Crochê!',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'Iv06hxKEylWFWJdmR3yz',
          media: ['https://i.ibb.co/r0P4TkQ/jett-img.jpg'],
          link: 'https://shopee.com.br/Jett-em-Croch%C3%AA-Amigurumi-de-Valorant-i.623543065.23697302314?sp_atk=74036619-2c06-48e2-95b3-a06bfb4eab0e&xptdk=74036619-2c06-48e2-95b3-a06bfb4eab0e',
          price: 85.3,
          product_group: 'Valorant',
          purchase_count: 1,
          rating: 0,
          tag: 'Jett - Valorant',
          title: 'Jett - Valorant',
          category_id: 3,
        },
        {
          created_at: 6,
          description: [
            '°❀⋆.ೃ࿔*:･ Leitão em crochê!',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'L7V7atTdkaqrAuXeaYDm',
          media: ['https://i.ibb.co/PDDqht8/leit-o.jpg'],
          link: 'https://shopee.com.br/Ursinho-Pooh-em-Croch%C3%AA-Amigurumi-Puff-Winnie-the-Pooh-Tigr%C3%A3o-I%C3%B3-e-Leit%C3%A3o-i.623543065.22792811817?sp_atk=13f39ccf-e645-4ba1-8f65-0d254b79939c&xptdk=13f39ccf-e645-4ba1-8f65-0d254b79939c',
          price: 49.9,
          product_group: 'Ursinho Pooh',
          purchase_count: 0,
          rating: 0,
          tag: 'Ursinho Pooh em Crochê Amigurumi Puff Winnie the Pooh Tigrão Ió e Leitão',
          title: 'Leitão',
          category_id: 4,
        },
        {
          created_at: 5,
          description: [
            '°❀⋆.ೃ࿔*:･ Tanjiro em crochê!',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'LzPYdkYWm6Qlhib8uwSW',
          media: ['https://i.ibb.co/TPQ0KdK/tanjiro-img.jpg'],
          link: 'https://shopee.com.br/Tanjiro-em-Croch%C3%AA-Amigurumi-de-Demon-Slayer-i.623543065.23297302681?sp_atk=22444519-9e25-4d0e-bba2-e21cae6111e0&xptdk=22444519-9e25-4d0e-bba2-e21cae6111e0',
          price: 92.9,
          product_group: 'Demon Slayer',
          purchase_count: 0,
          rating: 0,
          tag: 'Tanjiro Kamado - Demon Slayer Kimetsu no Yaiba',
          title: 'Tanjiro - Demon Slayer',
          category_id: 2,
        },
        {
          created_at: 9,
          description: [
            '°❀⋆.ೃ࿔*:･ Sangonomiya Kokomi em Crochê! ',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'MNs51dCrj3JUIHDbPFJ6',
          media: ['https://i.ibb.co/bBWzKF3/kokomi-img.jpg'],
          link: 'https://shopee.com.br/Sangonomiya-Kokomi-em-Croch%C3%AA-Amigurumi-de-Genshin-Impact-i.623543065.23992858719?sp_atk=76c4def1-2754-4769-9bca-803d60f2ac40&xptdk=76c4def1-2754-4769-9bca-803d60f2ac40',
          price: 165.9,
          product_group: 'Genshin Impact',
          purchase_count: 0,
          rating: 0,
          tag: 'Sangonomiya Kokomi - Genshin Impact',
          title: 'Sangonomiya Kokomi - Genshin Impact',
          category_id: 3,
        },
        {
          created_at: 3,
          description: [
            '°❀⋆.ೃ࿔*:･ Sage em crochê!',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'OPpSmWNTskpKWvF1fieG',
          media: ['https://i.ibb.co/z500nCn/sage-img.jpg'],
          link: 'https://shopee.com.br/Sage-em-croch%C3%AA-Amigurumi-de-Valorant-i.623543065.23497302181?sp_atk=6ad6e8a5-7dd4-4dd8-b913-6d8b4de571ce&xptdk=6ad6e8a5-7dd4-4dd8-b913-6d8b4de571ce',
          price: 92.9,
          product_group: 'Valorant',
          purchase_count: 1,
          rating: 0,
          tag: 'Sage - Valorant',
          title: 'Sage - Valorant',
          category_id: 3,
        },
        {
          created_at: 9,
          description: [
            '°❀⋆.ೃ࿔*:･ Shogun Raiden em Crochê! ',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'Oi53nwcL6nkVKDgLnwcD',
          media: ['https://i.ibb.co/cvDWZZh/raiden-1.jpg'],
          link: 'https://shopee.com.br/Shogun-Raiden-em-Croch%C3%AA-Ei-Baal-Amigurumi-de-Genshin-Impact-i.623543065.23997355293?sp_atk=b99404eb-2361-4495-9032-b2871478b352&xptdk=b99404eb-2361-4495-9032-b2871478b352',
          price: 165.9,
          product_group: 'Genshin Impact',
          purchase_count: 1,
          rating: 0,
          tag: 'Raiden Shogun Ei - Genshin Impact',
          title: 'Raiden Shogun - Genshin Impact',
          category_id: 3,
        },
        {
          created_at: 5,
          description: [
            '°❀⋆.ೃ࿔*:･ Zenitsu em crochê!',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'RzmSSSBFnVYqj15VNCNd',
          media: ['https://i.ibb.co/RBpQ6WZ/zenitsu-img.jpg'],
          link: 'https://shopee.com.br/Zenitsu-em-Croch%C3%AA-Amigurumi-de-Demon-Slayer-i.623543065.23392806062?sp_atk=3159b458-f0f7-47a4-8efc-9f831be5d5de&xptdk=3159b458-f0f7-47a4-8efc-9f831be5d5de',
          price: 92.9,
          product_group: 'Demon Slayer',
          purchase_count: 0,
          rating: 0,
          tag: 'Zenitsu - Demon Slayer Kimetsu no Yaiba',
          title: 'Zenitsu - Demon Slayer',
          category_id: 2,
        },
        {
          created_at: 2,
          description: [
            '𓆩ꨄ︎𓆪 A assassina (Rosa Selvagem) da família Forger em Crochê! Yor Forger! ⋆｡ﾟ☁︎｡⋆｡ ﾟ☾ ﾟ｡⋆',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'UDHKecBXtDLRFI4w8iQf',
          media: ['https://i.ibb.co/3z10szZ/yor-img.jpg'],
          link: 'https://shopee.com.br/Yor-Forger-em-Croch%C3%AA-Amigurumi-de-Spy-X-Family-Anya-Loid-Chaveiro-i.623543065.23697282109?sp_atk=469c2b52-0316-4463-b157-f338232b5333&xptdk=469c2b52-0316-4463-b157-f338232b5333',
          price: 92.9,
          product_group: 'Spy x Family',
          purchase_count: 0,
          rating: 0,
          tag: 'Yor Forger - Spy x Family',
          title: 'Yor Forger - Spy x Family',
          category_id: 2,
        },
        {
          created_at: 6,
          description: [
            '°❀⋆.ೃ࿔*:･ Tigrão em crochê!',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'UwCr95HInRNeBUpXm7Sx',
          media: ['https://i.ibb.co/68pK9Xd/tigrao.jpg'],
          link: 'https://shopee.com.br/Ursinho-Pooh-em-Croch%C3%AA-Amigurumi-Puff-Winnie-the-Pooh-Tigr%C3%A3o-I%C3%B3-e-Leit%C3%A3o-i.623543065.22792811817?sp_atk=13f39ccf-e645-4ba1-8f65-0d254b79939c&xptdk=13f39ccf-e645-4ba1-8f65-0d254b79939c',
          price: 49.9,
          product_group: 'Ursinho Pooh',
          purchase_count: 0,
          rating: 0,
          tag: 'Ursinho Pooh em Crochê Amigurumi Puff Winnie the Pooh Tigrão Ió e Leitão',
          title: 'Tigrão',
          category_id: 4,
        },
        {
          created_at: 6,
          description: [
            '°❀⋆.ೃ࿔*:･ Ió em crochê!',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'WB3OZR2HbIcsJ1cKretZ',
          media: ['https://i.ibb.co/6vCZFMd/i.jpg'],
          link: 'https://shopee.com.br/Ursinho-Pooh-em-Croch%C3%AA-Amigurumi-Puff-Winnie-the-Pooh-Tigr%C3%A3o-I%C3%B3-e-Leit%C3%A3o-i.623543065.22792811817?sp_atk=13f39ccf-e645-4ba1-8f65-0d254b79939c&xptdk=13f39ccf-e645-4ba1-8f65-0d254b79939c',
          price: 49.9,
          product_group: 'Ursinho Pooh',
          purchase_count: 0,
          rating: 0,
          tag: 'Ursinho Pooh em Crochê Amigurumi Puff Winnie the Pooh Tigrão Ió e Leitão',
          title: 'Ió',
          category_id: 4,
        },
        {
          created_at: 14,
          description: [
            '°❀⋆.ೃ࿔*:･ Nezuko dormindo em crochê!',
            'Tem aproximadamente 10 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'bMeCJI9x5zOZ9tH7J32H',
          media: [
            'https://i.ibb.co/k1DbQCs/nez]uko-dormindo-1.jpg',
            'https://i.ibb.co/L80JL9S/nezuko-dormindo-2.jpg',
            'https://i.ibb.co/C2DVv16/nezuko-dormindo-3.jpg',
          ],
          link: 'https://shopee.com.br/Nezuko-Dormindo-em-Croch%C3%AA-Amigurumi-de-Demon-Slayer-Nezuko-Kamado-i.623543065.23792991652?sp_atk=ec4c3cf9-f23e-45cd-b098-c9f583fc95d7&xptdk=ec4c3cf9-f23e-45cd-b098-c9f583fc95d7',
          price: 99.9,
          product_group: 'Demon Slayer',
          purchase_count: 0,
          rating: 0,
          tag: 'Nezuko Kamado - Demon Slayer Kimetsu no Yaiba',
          title: 'Nezuko Dormindo',
          category_id: 2,
        },
        {
          created_at: 13,
          description: [
            '°❀⋆.ೃ࿔*:･ Princesa Rapunzel em crochê!',
            'Tem aproximadamente 15 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'bhdQC0BcIZthOOvEUaey',
          media: ['https://i.ibb.co/XFQLS7m/rapunzel.jpg'],
          link: 'https://shopee.com.br/Rapunzel-Flynn-Pascal-em-Croch%C3%AA-Amigurumi-de-Enrolados-Princesas-Crochet-i.623543065.23097417301?sp_atk=9c84e44e-fe0e-41e3-b623-f43750121c00&xptdk=9c84e44e-fe0e-41e3-b623-f43750121c00',
          price: 290.9,
          product_group: 'Disney Princess',
          purchase_count: 1,
          rating: 0,
          tag: 'Rapunzel Flynn Pascal em Crochê Amigurumi de Enrolados Princesas Crochet',
          title: 'Rapunzel',
          category_id: 7,
        },
        {
          created_at: 5,
          description: [
            '°❀⋆.ೃ࿔*:･ Inosuke em crochê!',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'etEexkSRQU1cWTOaCsTD',
          media: ['https://i.ibb.co/37FWT5K/inosuke-img.jpg'],
          link: 'https://shopee.com.br/Inosuke-em-Croch%C3%AA-Amigurumi-de-Demon-Slayer-i.623543065.23197302949?sp_atk=46feb48d-746c-49fa-ae3e-a70717d6dc5d&xptdk=46feb48d-746c-49fa-ae3e-a70717d6dc5d',
          price: 92.9,
          product_group: 'Demon Slayer',
          purchase_count: 0,
          rating: 0,
          tag: 'Inosuke - Demon Slayer Kimetsu no Yaiba',
          title: 'Inosuke - Demon Slayer',
          category_id: 2,
        },
        {
          created_at: 1,
          description: [
            '⋆☾ ⋆🪐𐙚ִ ࣪𖤐⋆｡°✩ Chaveiro de mini Unicórnio Fofinho ☆✨🌕☆',
            'Tem aproximadamente de 5 a 6 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'kT8UXkY03c9gJmPr7dN8',
          media: ['https://i.ibb.co/MDYRwG1/unicornio-img.jpg'],
          link: 'https://shopee.com.br/Chaveiro-Mini-Unic%C3%B3rnio-Fofinho-em-Croch%C3%AA-Amigurumi-i.623543065.19797605152?sp_atk=4e5cafab-8a21-42fa-a299-fccdc42b4735&xptdk=4e5cafab-8a21-42fa-a299-fccdc42b4735',
          price: 21.9,
          product_group: 'animals',
          purchase_count: 1,
          rating: 0,
          tag: 'Chaveiro de Unicórnio - Animais',
          title: 'Chaveiro de Unicórnio',
          category_id: 4,
        },
        {
          created_at: 9,
          description: [
            '°❀⋆.ೃ࿔*:･ Yoimiya em crochê!',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'm8XFC9nhFg0x10fN45Cf',
          media: ['https://i.ibb.co/xSC4G38/yoimiya-HD.jpg'],
          link: 'https://shopee.com.br/Yoimiya-em-croch%C3%AA-Amigurumi-de-Genshin-Impact--i.623543065.22197368177?sp_atk=135a33bc-bb27-4a0c-bdd2-6b5b6d1575b9&xptdk=135a33bc-bb27-4a0c-bdd2-6b5b6d1575b9',
          price: 165.9,
          product_group: 'Genshin Impact',
          purchase_count: 0,
          rating: 0,
          tag: 'Yoimiya - Genshin Impact',
          title: 'Yoimiya - Genshin Impact',
          category_id: 3,
        },
        {
          created_at: 2,
          description: [
            '˚˖𓍢ִ໋🌷͙֒✧˚.🎀༘⋆ A filha telepata da família Forger em Crochê! ⋆˚🐾˖°',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'nZA3PRrrurAMCdSbpMFg',
          media: ['https://i.ibb.co/gw9qGqt/anya-img.jpg'],
          link: 'https://shopee.com.br/Anya-Forger-em-Croch%C3%AA-Amigurumi-de-Spy-X-Family-Yor-Loid-Chaveiro-i.623543065.23592785536?sp_atk=2b090b0d-445a-4592-a9b7-cf79673d720b&xptdk=2b090b0d-445a-4592-a9b7-cf79673d720b',
          price: 92.9,
          product_group: 'Spy x Family',
          purchase_count: 0,
          rating: 0,
          tag: 'Anya Forger - Spy x Family',
          title: 'Anya Forger - Spy x Family',
          category_id: 2,
        },
        {
          created_at: 6,
          description: [
            '°❀⋆.ೃ࿔*:･ Ursinho Pooh em crochê!',
            'Tem aproximadamente de 12 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'oSZv8YCTuTGf07w8292E',
          media: ['https://i.ibb.co/XbZF55H/pooh-img.jpg'],
          link: 'https://shopee.com.br/Ursinho-Pooh-em-Croch%C3%AA-Amigurumi-Puff-Winnie-the-Pooh-Tigr%C3%A3o-I%C3%B3-e-Leit%C3%A3o-i.623543065.22792811817?sp_atk=13f39ccf-e645-4ba1-8f65-0d254b79939c&xptdk=13f39ccf-e645-4ba1-8f65-0d254b79939c',
          price: 49.9,
          product_group: 'Ursinho Pooh',
          purchase_count: 0,
          rating: 0,
          tag: 'Ursinho Pooh em Crochê Amigurumi Puff Winnie the Pooh Tigrão Ió e Leitão',
          title: 'Ursinho Pooh',
          category_id: 4,
        },
        {
          created_at: 13,
          description: [],
          id: 'oX0bfrnh3eErfGG67tam',
          media: ['https://i.ibb.co/hWcb3Vt/cinderela.jpg'],
          link: 'https://shopee.com.br/Princesas-Disney-em-Croch%C3%AA-Anna-Elsa-Merida-Branca-de-Neve-Tiana-Ariel-Cinderela-Aurora-Vanellope-Bella-Moana-Amigurumi-Crochet-i.623543065.23297417406?sp_atk=84b78ba2-ae13-42a7-b40c-bfcf380cf92f&xptdk=84b78ba2-ae13-42a7-b40c-bfcf380cf92f',
          price: 159.9,
          product_group: 'Disney Princess',
          purchase_count: 0,
          rating: 0,
          tag: 'Princesas Disney em Crochê Cinderela',
          title: 'Cinderela',
          category_id: 7,
        },
        {
          created_at: 11,
          description: [],
          id: 'sGUFcPtwZ5xiQtf2TeBu',
          media: ['https://i.ibb.co/7nVsNCM/lulu-img.jpg'],
          link: 'https://shopee.com.br/Lulu-em-Croch%C3%AA-Amigurumi-de-League-Of-Legends-i.623543065.23797408512?xptdk=6271acac-15b5-46c3-adff-dfd1b35613dc',
          price: 129,
          product_group: 'League of Legends',
          purchase_count: 0,
          rating: 0,
          tag: 'Lulu em Crochê Amigurumi de League Of Legends LOL',
          title: 'Lulu - League of Legends',
          category_id: 3,
        },
        {
          created_at: 9,
          description: [
            '°❀⋆.ೃ࿔*:･ Hu Tao em crochê!',
            'Tem aproximadamente de 13 cm, olhos com trava e enchimento de fibra siliconada antialérgica.',
          ],
          id: 'sg2Grl46hcuNB0mAQ9Uy',
          media: ['https://i.ibb.co/j5JpBFY/hutao-img.jpg'],
          link: 'https://shopee.com.br/Hu-tao-em-Croch%C3%AA-Amigurumi-de-Genshin-Impact-i.623543065.18199215672?sp_atk=ddaa9e56-0f49-40af-b7b1-3c62c51e974c&xptdk=ddaa9e56-0f49-40af-b7b1-3c62c51e974c',
          price: 165.9,
          product_group: 'Genshin Impact',
          purchase_count: 0,
          rating: 0,
          tag: 'Hu Tao - Genshin Impact',
          title: 'Hu Tao - Genshin Impact',
          category_id: 3,
        },
        {
          created_at: 7,
          description: [],
          id: 'tJ2ezkutSyzqo9FRqbQV',
          media: ['https://i.ibb.co/M9jDZf1/baby-groot-img.jpg'],
          link: 'https://shopee.com.br/Baby-Groot-em-Croch%C3%AA-Amigurumi-Chaveiro-i.623543065.22792834877?sp_atk=8c0334fe-bc89-4ade-a230-3655c4758d3e&xptdk=8c0334fe-bc89-4ade-a230-3655c4758d3e',
          price: 21.5,
          product_group: 'Heroes',
          purchase_count: 0,
          rating: 0,
          tag: 'Baby Groot - Guardiões da Galáxia',
          title: 'Baby Groot - Guardiões da Galáxia',
          category_id: 6,
        },
        {
          created_at: 10,
          description: [],
          id: 'tKh6hfsAHITXZqWIiCTL',
          media: ['https://i.ibb.co/0rVgNJH/nossa-Senhora-Concei-o-img.jpg'],
          link: 'https://shopee.com.br/Nossa-Senhora-da-Concei%C3%A7%C3%A3o-em-Croch%C3%AA-Amigurumi-Religioso-Imaculada-i.623543065.23997380860?sp_atk=b9a5eea5-a28b-4b26-9840-2539e9d676b5&xptdk=b9a5eea5-a28b-4b26-9840-2539e9d676b5',
          price: 159.9,
          product_group: 'Religious',
          purchase_count: 1,
          rating: 0,
          tag: 'Nossa Senhora da Conceição em Crochê Amigurumi Religioso Imaculada',
          title: 'Nossa Senhora da Conceição',
          category_id: 5,
        },
        {
          created_at: 9,
          description: [],
          id: 'tPFBME3cX9HLQK3sRLER',
          media: ['https://i.ibb.co/f4DWDp5/ayakaHD.jpg'],
          link: 'https://shopee.com.br/Kamisato-Ayaka-em-Croch%C3%AA-Amigurumi-de-Genshin-Impact-i.623543065.23997350337?sp_atk=a1d50488-ee31-4fc8-a15e-4106f3090e25&xptdk=a1d50488-ee31-4fc8-a15e-4106f3090e25',
          price: 165.9,
          product_group: 'Genshin Impact',
          purchase_count: 0,
          rating: 0,
          tag: 'Kamisato Ayaka - Genshin Impact',
          title: 'Kamisato Ayaka - Genshin Impact',
          category_id: 3,
        },
        {
          created_at: 6,
          description: [],
          id: 'utaMHekFFaBXOqt3Qioc',
          media: ['https://i.ibb.co/bgW3BQ3/yodinha-img.jpg'],
          link: 'https://shopee.com.br/Baby-Yoda-em-Croch%C3%AA-Amigurumi-Grogu-i.623543065.23997307814?sp_atk=01d422d8-0731-4d05-9935-cc76a51b18ec&xptdk=01d422d8-0731-4d05-9935-cc76a51b18ec',
          price: 92.9,
          product_group: 'Star Wars',
          purchase_count: 0,
          rating: 0,
          tag: 'Baby Yoda - Star Wars',
          title: 'Baby Yoda - Star Wars',
          category_id: 6,
        },
        {
          created_at: 9,
          description: [],
          id: 'wceynzuLNmHEYOMtZsci',
          media: ['https://i.ibb.co/GdbJ4Hx/Ningguang.jpg'],
          link: 'https://shopee.com.br/Ningguang-em-Croch%C3%AA-Amigurumi-de-Genshin-Impact-i.623543065.22397363054?sp_atk=e7d194ae-041f-417e-a83d-74e4825d8345&xptdk=e7d194ae-041f-417e-a83d-74e4825d8345',
          price: 165.9,
          product_group: 'Genshin Impact',
          purchase_count: 0,
          rating: 0,
          tag: 'Ningguang - Genshin Impact',
          title: 'Ningguang - Genshin Impact',
          category_id: 3,
        },
        {
          created_at: 5,
          description: [],
          id: 'whLptTvHXzYaGhcxFayt',
          media: ['https://i.ibb.co/H2CRydD/nezuko-img.jpg'],
          link: 'https://shopee.com.br/Nezuko-em-Croch%C3%AA-Amigurumi-de-Demon-Slayer-i.623543065.23397302642?sp_atk=3d329d9e-4e3f-4f5b-8c94-84a412ec74c8&xptdk=3d329d9e-4e3f-4f5b-8c94-84a412ec74c8',
          price: 92.9,
          product_group: 'Demon Slayer',
          purchase_count: 0,
          rating: 0,
          tag: 'Nezuko Kamado - Demon Slayer Kimetsu no Yaiba',
          title: 'Nezuko - Demon Slayer',
          category_id: 2,
        },
      ],
    });

    console.log('Database seeded successfully!');
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });